### ISSUE TITLE
CShake Customisation string 

### ISSUE THREAD

**Issue by Frosne** [twiss/webcrypto-modern-algos#4]
From https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-185.pdf
Section 3. 

> S is a customization bit string. The user selects this string to define a variant of the
function. When no customization is desired, S is set to the empty string.

Should the customization in https://twiss.github.io/webcrypto-modern-algos/#cshake-params be optional? Or, should you specify that if no customization is provided, then the code will use an empty buffer?

**Comment by Frosne** [comment]
The same probably for functionName?

**Comment by twiss** [comment]
I've attempted to clarify this in https://github.com/twiss/webcrypto-modern-algos/commit/fdc62a1bef9863d94f5f9122488b39c9ba556a74 :) Thanks for pointing this out!
